app_navigator/urls.py
from django.urls import path

from . import views

app_name = "app_navigator"
urlpatterns = [
    path("", views.index, name = "index"),    
]

birthday/urls.py
from django.urls import path
from . import views

app_name = 'birthday'
urlpatterns = [
    path("", views.index, name = "index"),
]

django_learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("app_navigator.urls")),
    path("hello/", include("hello.urls")),
    path("birthday/", include("birthday.urls")),
    path("todo/", include("todo.urls")),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
]

flights/urls.py
from django.urls import path

from . import views

app_name = 'flights'
urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:flight_id>", views.single_flight, name = "single_flight"),
    path("book/<int:flight_id>", views.book, name = "book"),
]

hello/urls.py
from django.urls import path
from . import views

app_name = 'hello'
urlpatterns = [
    path("", views.index, name = "index"),
    path("<str:name>", views.greet, name = "greet"),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path("", views.index, name = "index"),
    path("add_task", views.add_task, name = "add_task"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout"),
    path("register", views.register_view, name = "register"),
]

app_navigator/models.py
from django.db import models

# Create your models here.

flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    city = models.CharField(max_length = 64)
    code = models.IntegerField()

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete = models.CASCADE, related_name = "departures")
    destination = models.ForeignKey(Airport, on_delete = models.CASCADE, related_name = "arrivals")
    duration = models.IntegerField()

    def is_valid_flight(self):
        return self.origin != self.destination and self.duration > 0

    def __str__(self):
        return f"{self.id} : {self.origin} to {self.destination}"

   
class Passenger(models.Model):
    first_name = models.CharField(max_length = 64)
    last_name = models.CharField(max_length = 64)
    flights = models.ManyToManyField(Flight, blank = True, related_name = "passengers")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

app_navigator/views.py
from django.shortcuts import render

from django_learning import settings

def filter_out_django_apps(apps):
    apps_result = [app for app in apps if 'django' not in app]
    apps_result.remove('app_navigator')
    return apps_result

def add_urls_to_app_names(apps):
    apps_result = []
    for app_name in apps:
        app_url = app_name + ":index"
        app = (app_name, app_url)
        apps_result.append(app)

    return apps_result

# Create your views here.
def index(request):
    apps = settings.INSTALLED_APPS
    apps = filter_out_django_apps(apps)    
    apps = add_urls_to_app_names(apps)
    return render(request, "app_navigator/index.html", {
        "apps" : apps
    })

birthday/views.py
from django.shortcuts import render

import datetime

# Create your views here.
def index(requst):
    now = datetime.datetime.now()
    is_my_birthday = now.month == 12 and now.day == 31
    return render(requst, "birthday/index.html", {
        "is_my_birthday": is_my_birthday   
    })

flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Flight, Passenger

# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flights" : Flight.objects.all()
    })

def single_flight(request, flight_id):
    try:
        flight = Flight.objects.get(pk = flight_id)
        return render(request, "flights/single_flight.html", {
            "flight" : flight,
            "passengers" : flight.passengers.all(),
            "non_passengers" : Passenger.objects.exclude(flights = flight).all(),
        })
    except Flight.DoesNotExist:
        return render(request, "flights/error.html", {
            "message" : "No flight with the given id"
        })

def book(request, flight_id):
    if request.method == 'POST':
        passenger_id = request.POST['passenger'] 
        passenger = Passenger.objects.get(pk = passenger_id)
        flight = Flight.objects.get(pk = flight_id)
        passenger.flights.add(flight)

        return HttpResponseRedirect(reverse('flights:single_flight', args = (flight_id,)))

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/hello.html")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name" : name.capitalize()
    })

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect 
from django.urls import reverse 
from django import forms

class Task_form(forms.Form):
    task = forms.CharField(label = 'New task', max_length = 20)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "todo/index.html", {
        "tasks": request.session["tasks"]
    })

def add_task(request):
    if request.method == 'POST':
        form = Task_form(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return render(request, "todo/add_task.html", {
                "form": form
            })

    return render(request, "todo/add_task.html", {
        "form": Task_form()
    })

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm 

def login_if_valid(request, username, password):
    user = authenticate(request, username = username, password = password)
    if user is not None:
        login(request, user)


# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return render(request, "users/authentication.html")
    
    return render(request, "users/welcome.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        login_if_valid(request, username, password)
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("users:index"))
        else:  
            return render(request, "users/login.html", {
                "message" : "Invalid Credentials!",
            })

    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message" : "Logged out!",
    })

def register_view(request):
    if (request.method == 'POST'):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            login_if_valid(request, username, password)
            return redirect('users:index')
        else:
            return render(request, 'users/register.html', {
                'form' : form
            })
    
    form = UserCreationForm()
    return render(request, 'users/register.html', {
        'form' : form
    })

app_navigator/templates/app_navigator/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head> 
        <title> App Navigator </title>
        <link href="{% static 'app_navigator/styles.css' %}" rel="stylesheet">
    </head>
    <bod> 
        <h1> Welcome To App Navigator </h1>
        <h3> Pick your app: </h3>
        <div id = "container">
            {% for app_name, app_url in apps %}
                {% url app_url as the_url %}
                {% if the_url  %}
                    <a href="{{ the_url }}"> {{ app_name }} </a>
                {% endif %}
            {% endfor %}
        </div>
    </bod>
</html>

birthday/templates/birthday/index.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title> is my birtday? </title>
        <link rel = "stylesheet" href = "{% static 'birthday/styles.css' %}">
    </head>
    <body> 
        {% if is_my_birthday %}
            <h1> Today is Osama's Birthday </h1>
        {% else %}
            <h1> It's not Osama's Birthday </h1>
        {% endif %}
    </body>
</html>

flights/templates/flights/error.html
{% extends 'flights/layout.html' %}

{% block body %}
    <div class="container mt-5">
        <h1>{{ message }}</h1>
    </div>
{% endblock %}

flights/templates/flights/index.html
{% extends 'flights/layout.html' %}

{% block body %}
    <div class="container mt-5">
        <h1 class="mb-4">Flights:</h1>
        <ul class="list-group">
            {% for flight in flights %}
                <li class="list-group-item mb-2">
                    <span class="font-weight-bold">{{ flight.id }}:</span>
                    {{ flight.origin }} to {{ flight.destination }}
                    <a href="{% url 'flights:single_flight' flight.id %}" class="btn btn-primary float-end">View Details</a>
                </li>
            {% empty %}
                <li class="list-group-item">No Flights Yet!</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

flights/templates/flights/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title> Flights </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'flights/styles.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

flights/templates/flights/single_flight.html
{% extends 'flights/layout.html' %}

{% block body %}
    <div class="container">
        <h1>{{ flight }}</h1>

        <h2 class="mt-4">Passengers</h2>
        <ol class="list-group">
            {% for passenger in passengers %}
                <li class="list-group-item">{{ passenger }}</li>
            {% empty %}
                <li class="list-group-item">No Passengers Yet!</li>
            {% endfor %}
        </ol>

        {% if non_passengers %}
            <h2 class="mt-4">Add Passenger</h2>
            <form action="{% url 'flights:book' flight.id %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <select name="passenger" class="form-select">
                        {% for passenger in non_passengers %}
                            <option value="{{ passenger.id }}">{{ passenger }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Book Passenger</button>
            </form>
        {% endif %}

        <a href="{% url 'flights:index' %}" class="btn btn-secondary mt-4">Go to all flights</a>
    </div>
{% endblock %}

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang = "en"> 
    <head> 
        <title> hello </title>    
    </head>
    <body>
        <h1> Hello, {{ name }}! </h1>
    </body>
</html>

hello/templates/hello/hello.html
<!DOCTYPE html>
<html lang = "en"> 
    <head> 
        <title> hello </title>    
    </head>
    <body>
        <h1> Hello, World! </h1>
    </body>
</html>

todo/templates/todo/add_task.html
{% extends "todo/layout.html" %}

{% block title %} Add task {% endblock %}

{% block body %}
    <h3 class = "gridclass">Add a task</h3>
    <form action="{% url 'todo:add_task' %}", method="post" id = "grid"> 
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    <br>
    <a href = "{% url 'todo:index' %}" class = "gridclass"> View tasks </a>
{% endblock %}

todo/templates/todo/index.html
{% extends "todo/layout.html" %}
{% block title %} tasks {% endblock %}

{% block body %}
    <h3 class = "gridclass"> TODO Tasks: </h3>
    <ul id = "grid">
        {% for task in tasks %}
            <li class = "gridclass"> {{ task }} </li>
        {% empty %}
            <li class = "gridclass"> No items. </li>
        {% endfor %}
    </ul>

    <a href = "{% url 'todo:add_task' %}" class="gridclass"> Add task </a>
{% endblock %}

todo/templates/todo/layout.html
{% load static %}

<!DOCTYPE html>
<html lang = "en">
    <head>
        <title> 
            {% block title %} 
            {% endblock %}
        </title>
        <link href="{% static 'todo/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %} 
        {% endblock %}
    </body>
</html>

users/templates/users/authentication.html
{% extends 'users/layout.html' %}

{% block body %}
    <h1> Please Login/Register: </h1>
    <ul>
        <li> 
            <a href="{% url 'users:login' %}"> Login </a>
        </li>
        <li>
            <a href="{% url 'users:register' %}"> Register </a>
        </li>
    </ul>
{% endblock body %}

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head> 
        <title> Users </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
    {% if message %}
        <h2> {{message}} </h2>
    {% endif %}
    
    <h1> Login </h1>
    <form action = "{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value = "login">  
    </form> 
{% endblock body %}

users/templates/users/register.html
{% extends 'users/layout.html' %}

{% block body %}
    <form action="{% url 'users:register' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    <br>
    <a href = "{% url 'users:login' %}"> Already have an account? </a>
{% endblock body %}
    

users/templates/users/welcome.html
{% extends 'users/layout.html' %}

{% block body %}
    {% if request.user.first_name %}
        <h1> Welcome {{request.user.first_name}}! </h1>    
    {% else %}
        <h1> Welcome {{request.user.username}}! </h1>    
    {% endif %}

    <a href="{% url 'users:logout' %}"> Logout </a>
{% endblock body %}